spring.application.name=verve_guard
spring.profiles.active=dev

server.port=${SERVER_PORT:8080}
spring.output.ansi.enabled=ALWAYS
logging.level.interswitch.academy=INFO
logging.level.com.zaxxer.hikari=WARN